Support LLaMA-7B deployment
Adlik/llma pull request #5
Opened 2023-06-29 06:50 UTC by xidianwym

2023-06-29 07:46 UTC, shiyingjin requested changes

2023-06-29 07:46 UTC, shiyingjin commented on llama_inference_service/llama/__init__.py
> +def is_torch_gcu_available():
函数放到这里不合适吧？所有的import如无特殊理由应该都放到文件最开始

2023-06-29 07:46 UTC, shiyingjin commented on llama_inference_service/llama/generation.py
> +torch.autograd.set_detect_anomaly(True)
这行为什么放到这里？

2023-06-29 07:46 UTC, shiyingjin commented on llama_inference_service/llama/generation.py
> +if is_torch_gcu_available():
为什么这里又有一个is_torch_gcu_available函数，和__init__中的是什么关系？

2023-07-03 01:52 UTC, xidianwym commented on llama_inference_service/llama/generation.py
> +if is_torch_gcu_available():
这里的is_torch_gcu_available()就是__init__中的is_torch_gcu_available()，from llama import is_torch_gcu_available这里将其导入

2023-07-07 08:52 UTC, shiyingjin approved these changes

2023-07-07 08:52 UTC, shiyingjin commented
bors r+

2023-07-10 00:52 UTC, shiyingjin commented
bors r+

2023-07-12 00:47 UTC, shiyingjin commented
bors r+

2023-07-12 02:15 UTC, closed without merging